### PR TITLE
Update I18nServiceProvider.php

### PR DESCRIPTION
**Pull request by RamyTalal**
Revert, this broke #12.

### CODE REVIEW

**Comment by iamgergo** [comment]
What is broken exactly?

**Comment by RamyTalal** [comment]
@iamgergo Only one package of a list of packages is translated. Basically the same bug in #12. When I reverted the code locally the issue was gone.

**Comment by RamyTalal** [comment]
@iamgergo Update: seems like a new issue. Unrelated to what I assumed.

afbeelding

**Comment by iamgergo** [comment]
Yes, it looks like your keys contain some special characters.

**Comment by RamyTalal** [comment]
It worked prior of the change. `\u0000*\u0000items` looks like the Laravel Collection is being encoded, I have seen this before.

**Comment by iamgergo** [comment]
I've never seen this. The `\u0000` is  `null` character: https://www.fileformat.info/info/unicode/char/0000/index.htm

**Comment by RamyTalal** [comment]
I know, this happens when the `items` property is being encoded. Adding `})->toArray();` on line 98 fixes the issue.

**Comment by iamgergo** [comment]
And what if you add the to array at the very end? Just before printing the translations?

**Comment by RamyTalal** [comment]
On line 101? I get `Call to a member function keys() on array`

**Comment by iamgergo** [comment]
Okay, thanks! I'll soon make the release if nothing comes in.

**Comment by RamyTalal** [comment]
Thank you!

**Comment by iamgergo** [comment]
As it turns out, this change breaks the code and the tests as well.

```
Call to a member function merge() on array at /.../I18nServiceProvider.php:73)
```

I reverted this change, so we need an other solution for that.

**Comment by RamyTalal** [comment]
What about the initial code? Does that fix it?

**Comment by iamgergo** [comment]
Probably not, I'll take a look. If it works well, then we bring back the old code.

**Comment by iamgergo** [comment]
Yes, please it would be a help. Thanks!

**Comment by RamyTalal** [comment]
See https://github.com/thepinecode/i18n/pull/22

**Pull request merged**
