### PR TITLE
Fix package translations structure

### PR DESCRIPTION
**Pull request by RamyTalal**
The output of the package translations is incorrect.

### CODE REVIEW

**Comment by iamgergo** [comment]
Can you send exactly that portion of the translations that contain the bad keys? I want to experiment a bit before changing the code again.

Thanks!

**Comment by RamyTalal** [comment]
@iamgergo Do you an email address to where I can send you the full JSON output?

**Comment by iamgergo** [comment]
No, just the key which gets endcoded badly and some values. If it's not confindential, you could send it here. For example:

```json
"key": {
     "otherkey": "value"
}
```

**Comment by RamyTalal** [comment]
Here is a snippet:
```json
"\u0000*\u0000items": {
        "shop::": {
            "articles": {
                "article": "Artikel",
            },
      }
}
```

I didn't specify `\u0000*\u0000items`. That happens when you try to serialize the `items` property of the Laravel Collection. If you remove `"\u0000*\u0000items": { ... }` the package translations work correctly again.

**Comment by iamgergo** [comment]
Okay, thanks! I can't reproduce this, but this does not mean that it won't happen again. Soon I'll release the new code.

**Comment by RamyTalal** [comment]
Thank you! I can email you the complete JSON output if you want? (I can't put it here, it's confidential).

**Comment by iamgergo** [comment]
I think it's fine, but thank you!

**Pull request merged**
